spring:
  application:
    name: clean-code-challenge
  datasource:
    url: jdbc:h2:mem:cleanCodeChallenge
    username: sa
    password: sa
    platform: h2
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: non-empty
server:
  servlet:
    context-path: /clean-code-challenge
 
 
